export const topicNameMap: Record<string, string> = {
    basic_syntax: "기초 문법",
    conditionals: "조건문",
    control_flow: "제어 흐름",
    data_structures: "자료 구조",
    data_types: "데이터 타입",
    exceptions: "예외 처리",
    file_io: "파일 입출력",
    functions: "함수",
    if_else: "if-else 조건문",
    loops: "반복문",
    operators: "연산자",
    string_methods: "문자열 메서드",
    strings: "문자열",
    variables: "변수",
};
