name: Build and Push to Docker Hub

on:
    push:
        branches:
            - main
            - develop

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        outputs:
            branch: ${{ steps.vars.outputs.raw_ref }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker image tags
              id: vars
              run: |
                  raw_ref="${GITHUB_REF_NAME}"
                  safe_ref="${raw_ref//\//-}"
                  SHORT_SHA=$(git rev-parse --short HEAD)
                  DATE_TAG=$(date +'%Y%m%d')

                  if [ "$raw_ref" = "main" ]; then
                    VERSION_TAG="${DATE_TAG}-${SHORT_SHA}"
                    echo "TAGS=heung115/spaghetti-fe:$VERSION_TAG,heung115/spaghetti-fe:latest" >> $GITHUB_ENV
                  else
                    echo "TAGS=heung115/spaghetti-fe:$safe_ref,heung115/spaghetti-fe:dev" >> $GITHUB_ENV
                  fi
                  echo "raw_ref=$raw_ref" >> $GITHUB_OUTPUT

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ env.TAGS }}

    call-update-k8s:
        needs: build-and-push
        uses: ./.github/workflows/kubeconfig.yaml
        with:
            branch: ${{ needs.build-and-push.outputs.branch }}
        secrets:
            K8S_CA: ${{ secrets.K8S_CA }}
            K8S_SERVER: ${{ secrets.K8S_SERVER }}
            K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
