name: Build and Push to Docker Hub

on:
    push:
        branches:
            - main
            - develop

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        outputs:
            branch: ${{ steps.vars.outputs.raw_ref }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # - name: Create .env.production
            #   run: |
            #       echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env.production
            #       echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
            #       echo "NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}" >> .env.production

            - name: Set up Docker image tags
              id: vars
              run: |
                  raw_ref="${GITHUB_REF_NAME}"
                  safe_ref="${raw_ref//\//-}"
                  SHORT_SHA=$(git rev-parse --short HEAD)
                  DATE_TAG=$(date +'%Y%m%d')

                  echo "raw_ref=$raw_ref" >> $GITHUB_OUTPUT
                  echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
                  echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
                  echo "safe_ref=$safe_ref" >> $GITHUB_ENV

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Main (Frontend)
              if: ${{ steps.vars.outputs.raw_ref == 'main' }}
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      heung115/spaghetti-fe:latest
                      heung115/spaghetti-fe:${{ env.DATE_TAG }}-${{ env.SHORT_SHA }}
                  build-args: |
                      NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
                      NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL_PROD }}
                      NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL_PROD }}

            - name: Build and Push Main (Back)
              if: ${{ steps.vars.outputs.raw_ref == 'main' }}
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      heung115/spaghetti-fe:latest-back
                  build-args: |
                      NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
                      NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL_BACK }}
                      NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL_BACK }}

            - name: Build and Push Dev
              if: ${{ steps.vars.outputs.raw_ref != 'main' }}
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      heung115/spaghetti-fe:${{ env.safe_ref }}
                      heung115/spaghetti-fe:dev
                  build-args: |
                      NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
                      NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}
                      NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

    call-update-k8s:
        needs: build-and-push
        uses: ./.github/workflows/kubeconfig.yaml
        with:
            branch: ${{ needs.build-and-push.outputs.branch }}
        secrets:
            K8S_CA: ${{ secrets.K8S_CA }}
            K8S_SERVER: ${{ secrets.K8S_SERVER }}
            K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
