name: update k8s pod image

on:
    workflow_call:
        inputs:
            branch:
                required: true
                type: string
        secrets:
            K8S_CA:
                required: true
            K8S_SERVER:
                required: true
            K8S_TOKEN:
                required: true

    workflow_dispatch:

jobs:
    setup-kubeconfig:
        runs-on: ubuntu-latest
        steps:
            # - name: get branch name
            #   id: vars
            #   run: |
            #       raw_ref="${GITHUB_REF_NAME}"
            #       safe_ref="${raw_ref//\//-}"
            #       echo "raw_ref=${raw_ref}" >> $GITHUB_OUTPUT
            #       echo "safe_ref=${safe_ref}" >> $GITHUB_OUTPUT

            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: "latest"

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "latest"

            - name: Set up kubeconfig
              run: |
                  mkdir -p ~/.kube
                  cat <<-EOF > ~/.kube/config
                  apiVersion: v1
                  kind: Config
                  clusters:
                  - cluster:
                      certificate-authority-data: "${{ secrets.K8S_CA }}"
                      server: "${{ secrets.K8S_SERVER }}"
                    name: github-cluster
                  contexts:
                  - context:
                      cluster: github-cluster
                      user: github-deployer
                    name: github-context
                  current-context: github-context
                  users:
                  - name: github-deployer
                    user:
                      token: "${{ secrets.K8S_TOKEN }}"
                  EOF

            - name: Print kubeconfig (debug)
              if: ${{ inputs.debug }}
              run: |
                  echo "===== KUBECONFIG ====="
                  cat ~/.kube/config
                  echo "======================"

            - name: update pod image
              run: |
                  BRANCH_NAME="${{ inputs.branch }}"
                  echo "Branch: $BRANCH_NAME"

                  if [ "$BRANCH_NAME" = "main" ]; then
                    echo "Restarting deployment for main branch"
                    kubectl rollout restart deployment backend-prod -n prod
                    kubectl rollout restart deployment nextjs-prod-web -n prod
                    # kubectl rollout restart statefulset postgresql-prod -n prod

                    kubectl rollout restart deployment nextjs-dev-back-web -n dev-back

                  else
                    echo "Restarting deployment for feature branch"
                    kubectl rollout restart deployment nextjs-dev-front-web -n dev-front
                  fi
